import type { Question } from "./types";

export const questionBank: Question[] = [
  {
    id: "q1",
    question: "What is the capital of Canada?",
    options: ["Toronto", "Ottawa", "Vancouver", "Montreal"],
    answer: "Ottawa",
    explanation: "Ottawa is the capital of Canada. Toronto is the largest city, but it isn't the capital.",
    category: "general-knowledge",
  },
  {
    id: "q2",
    question: "Which continent is the Sahara Desert located on?",
    options: ["Asia", "Africa", "Australia", "South America"],
    answer: "Africa",
    explanation: "The Sahara stretches across most of North Africa, making it the largest hot desert in the world.",
    category: "general-knowledge",
  },
  {
    id: "q3",
    question: "How many continents are there on Earth?",
    options: ["5", "6", "7", "8"],
    answer: "7",
    explanation: "The seven continents are Africa, Antarctica, Asia, Australia, Europe, North America, and South America.",
    category: "general-knowledge",
  },
  {
    id: "q4",
    question: "Which ocean is the largest in the world?",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
    answer: "Pacific",
    explanation: "The Pacific Ocean covers more area than all the continents combined.",
    category: "general-knowledge",
  },
  {
    id: "q5",
    question: "What planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    answer: "Mars",
    explanation: "Mars looks red because iron oxide, or rust, covers much of its surface.",
    category: "science",
  },
  {
    id: "q6",
    question: "What gas do plants absorb from the air to make food?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    answer: "Carbon Dioxide",
    explanation: "Plants use carbon dioxide, water, and sunlight to make their own food through photosynthesis.",
    category: "science",
  },
  {
    id: "q7",
    question: "What is the boiling point of water at sea level, in Celsius?",
    options: ["90°C", "100°C", "110°C", "120°C"],
    answer: "100°C",
    explanation: "At sea level, water boils at exactly 100°C (212°F).",
    category: "science",
  },
  {
    id: "q8",
    question: "What is 7 × 8?",
    options: ["54", "56", "58", "64"],
    answer: "56",
    explanation: "7 × 8 = 56.",
    category: "mathematics",
  },
  {
    id: "q9",
    question: "What is the value of Pi rounded to two decimal places?",
    options: ["3.14", "3.41", "3.12", "3.16"],
    answer: "3.14",
    explanation: "Pi (π) is approximately 3.14159, which rounds to 3.14.",
    category: "mathematics",
  },
  {
    id: "q10",
    question: "A triangle has angles of 90° and 45°. What is the third angle?",
    options: ["30°", "45°", "60°", "90°"],
    answer: "45°",
    explanation: "A triangle's angles always add up to 180°, so 180 − 90 − 45 = 45°.",
    category: "mathematics",
  },
];